name: Deploy
on:
  push:
    branches: deno
  pull_request:
    branches: deno

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install NPM Dependencies
        run: npm install
      
      - name: Build Deno Server
        run: npm run build
      
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "soft-moth-56"
          entrypoint: "https://deno.land/std@0.188.0/http/file_server.ts" # 📝 Update the entrypoint
          root: "dist"

